server:
  port: 8082

spring:
  application:
    name: admin-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ratelimiter_admin
    username: postgres
    password: <redacted>

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

jwt:
  secret: ${JWT_SECRET:SuperSecretKeyForJwtSigningThatIsAtLeast256BitsLong!!}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html